### ISSUE TITLE
Waiting for Worker to  catch up.

### ISSUE THREAD

**Issue by Nobrumski** [four-o-four/omniverse#12]
I seem to be seeing this a lot since the last update. I even tried restarting this morning and I am seeing the same message almost immediately repeated.

(INFO): Producer Thread has has too many articles (34520). Waiting for Worker to catch up.

I don't know if there is actually an issue or if I just happened to notice it for the first time.

**Comment by four-o-four** [comment]
Actually not an issue. There are two threads, one that dowloands the headers and one that proceeses them and puts them in the database. The process that downloads headers works alot faster than the other so if it doesnt wait once in awhile, the system may run out of resources. Now that I'm happy that the proceeses are cooperating, I will take those warnings out.

Thanks for the report! Keep them coming.

_Sent via Hubroid_

**Comment by Nobrumski** [comment]
Ok cool. I was just seeing it a ton and wasn't sure if the worker was stuck.
On Mar 27, 2012 10:59 AM, "four-o-four" <
reply@reply.github.com>
wrote:

**Comment by Nobrumski** [comment]
I still think there might be an issue. I came home to this after it was running all day. (INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.
(INFO): Producer Thread has has too many articles (42533). Waiting for Worker to
 catch up.

It was just sitting there. I then hit configuration just to make sure it wasn't locked up, which it wasn't, and then went to browse, and it started up again repeating.

**Comment by four-o-four** [comment]
That means that the thread thats storing the headers into the database got clobbered somehow. The number (42533) are how many articles are pending to be stored and clearly its not working. I'll an update soon where I'll take those messages out and add in some exception handling/reporting and see what happened. 

BTW, what os are you using?

**Comment by Nobrumski** [comment]
Ok cool. I am using win 7 ultimate 64 bit and python 2.6

I restarted it this morning and it looks like the count is actually going down for now so not sure what happened.

**Comment by four-o-four** [comment]
I was wondering about your os because I know some people are having issues with linux. I'll need to set up a machine so I can start doing testing for it.

I posted a commit with better exception reporting so if there was a problem, we should be able to find it in the log. Also it turns off all of those "Waiting...." messages.

More than likely it died trying to process a message and when you restarted it may have restarted ahead of the bad message. I went through this when I first started developing omniverse. It was chug along fine until it hit that one message that was formatted badly and poof.

**Comment by Nobrumski** [comment]
I am thinking it might be a specific message. It was stuck again today when I got home, but at a different number. It ran fine when I was leaving for work. 

Just saw this after updating
Exception in thread ArticleWorker-44090352:
Traceback (most recent call last):
  File "C:\Python26\lib\threading.py", line 532, in __bootstrap_inner
    self.run()
  File "C:\Omniverse\Omniverse2\omniverse\omniverse.py", line 103, in run
    if self.add_segment(subject, _from, message_id, date, lines, group):
  File "C:\Omniverse\Omniverse2\omniverse\omniverse.py", line 150, in add_segmen
t
    size = int(lines) \* 45
ValueError: invalid literal for int() with base 10: ''
