### ISSUE TITLE
Problems with the http server response

### ISSUE THREAD

**Issue by theotocopulitos** [four-o-four/omniverse#2]
The program works fine regarding the download of headers (after changes as per issue#1), but opening the browser and trying to connect to the cherrypy server delivers this message on the brower:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Users\xbmc.PERSONAL\Downloads\four-o-four-omniverse-a03cf17\four-o-four-omniverse-a03cf17\cherrypy_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Users\xbmc.PERSONAL\Downloads\four-o-four-omniverse-a03cf17\four-o-four-omniverse-a03cf17\cherrypy\lib\encoding.py", line 188, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Users\xbmc.PERSONAL\Downloads\four-o-four-omniverse-a03cf17\four-o-four-omniverse-a03cf17\cherrypy_cpdispatch.py", line 34, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Users\xbmc.PERSONAL\Downloads\four-o-four-omniverse-a03cf17\four-o-four-omniverse-a03cf17\web.py", line 7, in index
    return self.browse(pg, sz)
  File "C:\Users\xbmc.PERSONAL\Downloads\four-o-four-omniverse-a03cf17\four-o-four-omniverse-a03cf17\web.py", line 37, in browse
    result_set = connection.select(
AttributeError: 'NoneType' object has no attribute 'select'

**Comment by Nobrumski** [comment]
I just did a new pull and it looks like I am getting the same issue.

Traceback (most recent call last):
  File "C:\Omniverse\omniverse\cherrypy_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "C:\Omniverse\omniverse\cherrypy\lib\encoding.py", line 188, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Omniverse\omniverse\cherrypy_cpdispatch.py", line 34, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Omniverse\omniverse\web.py", line 7, in index
    return self.browse(pg, sz)
  File "C:\Omniverse\omniverse\web.py", line 37, in browse
    result_set = connection.select(
AttributeError: 'NoneType' object has no attribute 'select'

**Comment by four-o-four** [comment]
Fixed: https://github.com/four-o-four/omniverse/commit/3a7447f39d623ada09e3c2e7f4081f85153444ab

Thanks!
